console.log('Hello')
console.log('Mohseen18')
console.log('How are you')
console.log('How is your day going')
console.log('Where do you live')
console.log('What are your hobbies')
console.log('How old are you')
console.log('What is your fav food')